# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='api',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tapi.proto\x12\x03\x61pi\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/descriptor.proto\x1a\x1bgoogle/protobuf/empty.proto\"3\n\x0eResponseErrors\x12!\n\x05value\x18\x01 \x03(\x0b\x32\x12.api.ResponseError\" \n\rResponseError\x12\x0f\n\x07message\x18\x01 \x01(\t\"T\n\x12TranslateTextInput\x12\x17\n\x0fsource_language\x18\x01 \x01(\t\x12\x17\n\x0ftarget_language\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"b\n\x15TranslateTextResponse\x12$\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x16.api.TranslateTextData\x12#\n\x06\x65rrors\x18\x02 \x01(\x0b\x32\x13.api.ResponseErrors\":\n\x11TranslateTextData\x12\x0c\n\x04took\x18\x01 \x01(\x02\x12\x17\n\x0ftranslated_text\x18\x02 \x01(\t\"M\n\x14TranslateTextRequest\x12\x35\n\x14translate_text_input\x18\x01 \x01(\x0b\x32\x17.api.TranslateTextInput2|\n\x03\x41pi\x12u\n\rTranslateText\x12\x19.api.TranslateTextRequest\x1a\x1a.api.TranslateTextResponse\"-\x82\xd3\xe4\x93\x02\'\"\x0f/translate_text:\x14translate_text_inputb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_RESPONSEERRORS = _descriptor.Descriptor(
  name='ResponseErrors',
  full_name='api.ResponseErrors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='api.ResponseErrors.value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=162,
)


_RESPONSEERROR = _descriptor.Descriptor(
  name='ResponseError',
  full_name='api.ResponseError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='api.ResponseError.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=196,
)


_TRANSLATETEXTINPUT = _descriptor.Descriptor(
  name='TranslateTextInput',
  full_name='api.TranslateTextInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source_language', full_name='api.TranslateTextInput.source_language', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_language', full_name='api.TranslateTextInput.target_language', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='api.TranslateTextInput.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=282,
)


_TRANSLATETEXTRESPONSE = _descriptor.Descriptor(
  name='TranslateTextResponse',
  full_name='api.TranslateTextResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='api.TranslateTextResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errors', full_name='api.TranslateTextResponse.errors', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=382,
)


_TRANSLATETEXTDATA = _descriptor.Descriptor(
  name='TranslateTextData',
  full_name='api.TranslateTextData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='took', full_name='api.TranslateTextData.took', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='translated_text', full_name='api.TranslateTextData.translated_text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=442,
)


_TRANSLATETEXTREQUEST = _descriptor.Descriptor(
  name='TranslateTextRequest',
  full_name='api.TranslateTextRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='translate_text_input', full_name='api.TranslateTextRequest.translate_text_input', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=444,
  serialized_end=521,
)

_RESPONSEERRORS.fields_by_name['value'].message_type = _RESPONSEERROR
_TRANSLATETEXTRESPONSE.fields_by_name['data'].message_type = _TRANSLATETEXTDATA
_TRANSLATETEXTRESPONSE.fields_by_name['errors'].message_type = _RESPONSEERRORS
_TRANSLATETEXTREQUEST.fields_by_name['translate_text_input'].message_type = _TRANSLATETEXTINPUT
DESCRIPTOR.message_types_by_name['ResponseErrors'] = _RESPONSEERRORS
DESCRIPTOR.message_types_by_name['ResponseError'] = _RESPONSEERROR
DESCRIPTOR.message_types_by_name['TranslateTextInput'] = _TRANSLATETEXTINPUT
DESCRIPTOR.message_types_by_name['TranslateTextResponse'] = _TRANSLATETEXTRESPONSE
DESCRIPTOR.message_types_by_name['TranslateTextData'] = _TRANSLATETEXTDATA
DESCRIPTOR.message_types_by_name['TranslateTextRequest'] = _TRANSLATETEXTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResponseErrors = _reflection.GeneratedProtocolMessageType('ResponseErrors', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEERRORS,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.ResponseErrors)
  })
_sym_db.RegisterMessage(ResponseErrors)

ResponseError = _reflection.GeneratedProtocolMessageType('ResponseError', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEERROR,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.ResponseError)
  })
_sym_db.RegisterMessage(ResponseError)

TranslateTextInput = _reflection.GeneratedProtocolMessageType('TranslateTextInput', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATETEXTINPUT,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.TranslateTextInput)
  })
_sym_db.RegisterMessage(TranslateTextInput)

TranslateTextResponse = _reflection.GeneratedProtocolMessageType('TranslateTextResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATETEXTRESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.TranslateTextResponse)
  })
_sym_db.RegisterMessage(TranslateTextResponse)

TranslateTextData = _reflection.GeneratedProtocolMessageType('TranslateTextData', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATETEXTDATA,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.TranslateTextData)
  })
_sym_db.RegisterMessage(TranslateTextData)

TranslateTextRequest = _reflection.GeneratedProtocolMessageType('TranslateTextRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATETEXTREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.TranslateTextRequest)
  })
_sym_db.RegisterMessage(TranslateTextRequest)



_API = _descriptor.ServiceDescriptor(
  name='Api',
  full_name='api.Api',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=523,
  serialized_end=647,
  methods=[
  _descriptor.MethodDescriptor(
    name='TranslateText',
    full_name='api.Api.TranslateText',
    index=0,
    containing_service=None,
    input_type=_TRANSLATETEXTREQUEST,
    output_type=_TRANSLATETEXTRESPONSE,
    serialized_options=b'\202\323\344\223\002\'\"\017/translate_text:\024translate_text_input',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_API)

DESCRIPTOR.services_by_name['Api'] = _API

# @@protoc_insertion_point(module_scope)
